In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("customer_churn.csv")

In [3]:
df.head

<bound method NDFrame.head of      customer_id   age  annual_income  tenure_months  monthly_spend  \
0           1001  34.0       470994.0           49.0        36974.0
1           1002  41.0       372922.0           14.0        25882.0
2           1003  40.0       143257.0           15.0        32210.0
3           1004  28.0       236419.0           31.0        28136.0
4           1005  27.0       394022.0            1.0        15709.0
..           ...   ...            ...            ...            ...
116         1117  52.0       288791.0            8.0        11252.0
117         1118  45.0       210429.0            4.0        36972.0
118         1119  60.0       282206.0            4.0        34181.0
119         1120  21.0       324820.0           56.0         6944.0
120         1013  58.0       257269.0           24.0        35074.0

     support_calls  orders_last_6_months contract_type         region  churn
0              1.0                   5.0       Monthly          Abuja      0
1              4.0                   4.0        Annual  Port Harcourt      0
2              4.0                   8.0     Quarterly          Lagos      0
3              5.0                  14.0     Quarterly          Lagos      0
4              3.0                   4.0       Monthly          Lagos      0
..             ...                   ...           ...            ...    ...
116            7.0                   7.0        Annual  Port Harcourt      0
117            5.0                   9.0       Monthly          Lagos      0
118            2.0                   4.0        Annual  Port Harcourt      0
119            1.0                   7.0     Quarterly          Lagos      0
120            3.0                   8.0        Annual          Enugu      1

[121 rows x 10 columns]>

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
customer_id,121.0,1060.107438,34.907927,1001.0,1030.00,1060.0,1090.00,1120.0
age,120.0,42.050000,12.080855,-4.0,33.75,43.5,52.00,60.0
annual_income,120.0,296873.183333,158435.009081,70000.0,229504.25,282048.0,336580.00,1800000.0
tenure_months,121.0,34.586777,21.315358,1.0,16.00,33.0,53.00,72.0
monthly_spend,120.0,29194.516667,9912.890826,6944.0,23913.75,29947.0,34888.25,51550.0
support_calls,121.0,3.090909,2.077659,-2.0,2.00,3.0,4.00,10.0
orders_last_6_months,121.0,7.735537,2.971444,1.0,6.00,8.0,10.00,16.0
churn,121.0,0.214876,0.412444,0.0,0.00,0.0,0.00,1.0

In [5]:
df.head(5)

,customer_id,age,annual_income,tenure_months,monthly_spend,support_calls,orders_last_6_months,contract_type,region,churn
0,1001,34.0,470994.0,49.0,36974.0,1.0,5.0,Monthly,Abuja,0
1,1002,41.0,372922.0,14.0,25882.0,4.0,4.0,Annual,Port Harcourt,0
2,1003,40.0,143257.0,15.0,32210.0,4.0,8.0,Quarterly,Lagos,0
3,1004,28.0,236419.0,31.0,28136.0,5.0,14.0,Quarterly,Lagos,0
4,1005,27.0,394022.0,1.0,15709.0,3.0,4.0,Monthly,Lagos,0

In [6]:
df.tail(5)

,customer_id,age,annual_income,tenure_months,monthly_spend,support_calls,orders_last_6_months,contract_type,region,churn
116,1117,52.0,288791.0,8.0,11252.0,7.0,7.0,Annual,Port Harcourt,0
117,1118,45.0,210429.0,4.0,36972.0,5.0,9.0,Monthly,Lagos,0
118,1119,60.0,282206.0,4.0,34181.0,2.0,4.0,Annual,Port Harcourt,0
119,1120,21.0,324820.0,56.0,6944.0,1.0,7.0,Quarterly,Lagos,0
120,1013,58.0,257269.0,24.0,35074.0,3.0,8.0,Annual,Enugu,1

In [7]:
df.info

<bound method DataFrame.info of      customer_id   age  annual_income  tenure_months  monthly_spend  \
0           1001  34.0       470994.0           49.0        36974.0
1           1002  41.0       372922.0           14.0        25882.0
2           1003  40.0       143257.0           15.0        32210.0
3           1004  28.0       236419.0           31.0        28136.0
4           1005  27.0       394022.0            1.0        15709.0
..           ...   ...            ...            ...            ...
116         1117  52.0       288791.0            8.0        11252.0
117         1118  45.0       210429.0            4.0        36972.0
118         1119  60.0       282206.0            4.0        34181.0
119         1120  21.0       324820.0           56.0         6944.0
120         1013  58.0       257269.0           24.0        35074.0

     support_calls  orders_last_6_months contract_type         region  churn
0              1.0                   5.0       Monthly          Abuja      0
1              4.0                   4.0        Annual  Port Harcourt      0
2              4.0                   8.0     Quarterly          Lagos      0
3              5.0                  14.0     Quarterly          Lagos      0
4              3.0                   4.0       Monthly          Lagos      0
..             ...                   ...           ...            ...    ...
116            7.0                   7.0        Annual  Port Harcourt      0
117            5.0                   9.0       Monthly          Lagos      0
118            2.0                   4.0        Annual  Port Harcourt      0
119            1.0                   7.0     Quarterly          Lagos      0
120            3.0                   8.0        Annual          Enugu      1

[121 rows x 10 columns]>

In [8]:
print("Shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
df.info()

Shape: (121, 10)

Column names:
['customer_id', 'age', 'annual_income', 'tenure_months', 'monthly_spend', 'support_calls', 'orders_last_6_months', 'contract_type', 'region', 'churn']

Data types:
<class 'pandas.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           121 non-null    int64
 1   age                   120 non-null    float64
 2   annual_income         120 non-null    float64
 3   tenure_months         121 non-null    float64
 4   monthly_spend         120 non-null    float64
 5   support_calls         121 non-null    float64
 6   orders_last_6_months  121 non-null    float64
 7   contract_type         120 non-null    str
 8   region                121 non-null    str
 9   churn                 121 non-null    int64
dtypes: float64(6), int64(2), str(2)
memory usage: 9.6 KB

In [9]:
df.isnull().sum().sort_values(ascending=False)

age                     1
annual_income           1
contract_type           1
monthly_spend           1
customer_id             0
tenure_months           0
support_calls           0
orders_last_6_months    0
region                  0
churn                   0
dtype: int64

In [10]:
missing = df.isnull().sum().sort_values(ascending=False) 
missing_pct = (df.isnull().mean()*100).sort_values(ascending=False)

missing_report = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct.round(2)
})

missing_report

                      missing_count  missing_percent
age                               1             0.83
annual_income                     1             0.83
contract_type                     1             0.83
monthly_spend                     1             0.83
customer_id                       0             0.00
tenure_months                     0             0.00
support_calls                     0             0.00
orders_last_6_months              0             0.00
region                            0             0.00
churn                             0             0.00

In [11]:
for col in ["age", "annual_income", "monthly_spend"]:
    df[col] =df[col].fillna(df[col].median())

df["contract_type"] =df["contract_type"].fillna("Unknown")
df.isnull().sum()

customer_id             0
age                     0
annual_income           0
tenure_months           0
monthly_spend           0
support_calls           0
orders_last_6_months    0
contract_type           0
region                  0
churn                   0
dtype: int64

In [12]:
print("Number of duplicated rows:", df.duplicated().sum())
df[df.duplicated(keep=False)].sort_values("customer_id")

Number of duplicated rows: 1

,customer_id,age,annual_income,tenure_months,monthly_spend,support_calls,orders_last_6_months,contract_type,region,churn
12,1013,58.0,257269.0,24.0,35074.0,3.0,8.0,Annual,Enugu,1
120,1013,58.0,257269.0,24.0,35074.0,3.0,8.0,Annual,Enugu,1

In [13]:
df = df.drop_duplicates()
print("Duplicate rows after cleaning:",df.duplicated().sum())

Duplicate rows after cleaning: 0

In [14]:
print(df["region"].value_counts(dropna=False))

region
Lagos            35
Port Harcourt    27
Enugu            25
Abuja            18
Ibadan           11
lagos             1
LAGOS             1
enugu             1
ENUGU             1
Name: count, dtype: int64

In [15]:
df["region"] = (
    df["region"]
    .astype("string")
    .str.strip()
    .str.title()
)

df["region"].value_counts(dropna=False)

region
Lagos            37
Port Harcourt    27
Enugu            27
Abuja            18
Ibadan           11
Name: count, dtype: Int64

In [16]:
print("Invalid ages: ")
display(df[df["age"] < 0])

print("Invalid support-call counts: ")
display(df[df["support_calls"] < 0])

Invalid ages:

,customer_id,age,annual_income,tenure_months,monthly_spend,support_calls,orders_last_6_months,contract_type,region,churn
63,1064,-4.0,281890.0,1.0,29307.0,1.0,11.0,Monthly,Port Harcourt,1

Invalid support-call counts:

,customer_id,age,annual_income,tenure_months,monthly_spend,support_calls,orders_last_6_months,contract_type,region,churn
74,1075,34.0,384230.0,34.0,44623.0,-2.0,11.0,Quarterly,Enugu,1

In [17]:
df.loc[df["age"] < 0, "age"] = np.nan
df.loc[df["support_calls"] < 0, "support_calls"] = np.nan

df["age"] = df["age"].fillna(df["age"].median())
df["support_calls"] = df["support_calls"].fillna(df["support_calls"].median())

df[["age", "support_calls"]].describe()

              age  support_calls
count  120.000000     120.000000
mean    42.325000       3.133333
std     11.222661       2.033060
min     21.000000       0.000000
25%     34.000000       2.000000
50%     43.500000       3.000000
75%     52.000000       4.000000
max     60.000000      10.000000

In [18]:
Q1 = df["annual_income"].quantile(0.25)
Q3 = df["annual_income"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["annual_income"] < lower) |
    (df["annual_income"] > upper)
]

print("Lower bound:", lower)
print("Upper bound:", upper)

display(outliers)

Lower bound: 68890.625
Upper bound: 497193.625

,customer_id,age,annual_income,tenure_months,monthly_spend,support_calls,orders_last_6_months,contract_type,region,churn
88,1089,35.0,1800000.0,51.0,49509.0,1.0,10.0,Annual,Lagos,0

In [19]:
print("Missing Values:")
display(df.isnull().sum())

print("Duplicate rows:", df.duplicated().sum())

print("Negative ages:", (df["age"] < 0).sum())
print("Negative support calls:", (df["support_calls"] < 0).sum())

print("\nRegions:")
display(df["region"].value_counts())

Missing Values:

customer_id             0
age                     0
annual_income           0
tenure_months           0
monthly_spend           0
support_calls           0
orders_last_6_months    0
contract_type           0
region                  0
churn                   0
dtype: int64

Duplicate rows: 0
Negative ages: 0
Negative support calls: 0

Regions:

region
Lagos            37
Port Harcourt    27
Enugu            27
Abuja            18
Ibadan           11
Name: count, dtype: Int64

In [20]:
df.to_csv("customer_churn_cleande.csv", index=False)
print("Saved:", "customer_churn_cleaned.csv")
print("Final shape: ", df.shape)

Saved: customer_churn_cleaned.csv
Final shape:  (120, 10)